apiVersion: v1
kind: ConfigMap
metadata:
  name: app-variables
data:
  #env variables for the postgres component
  POSTGRES_USER: postgres
  POSTGRES_DB: app

  #env variables for the backend component
  DJANGO_ENV: development
  DEBUG: "1"
  SECRET_KEY: secretsecretsecretsecretsecret
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_ADMIN_USER: admin
  DJANGO_ADMIN_EMAIL: "admin@example.com"

  DATABASE: postgres
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: app
  DB_USER: postgres
  DB_HOST: postgres-cluster-ip-service
  DB_PORT: "5432"